src/api/base.ts
=> fix: moveEntity

src/extension.ts, src/utils/compileLogParser.ts, src/utils/compileManager.ts
Done:   Use a regex to extract basic error from output.log
Left to do:
=> add compile error display

package-lock.json, package.json, src/provider/remoteFileSystemProvider.ts
=> remove Diff

src/api/socketio.ts, src/provider/remoteFileSystemProvider.ts
As #23 mentioned, disconnected socketio does not reconnect. To enable socketio reconnecting feature, modifications includes: 
- `src/api/socketio.ts` : add resumeHandlers function, add disconnected handler
- `src/provider/remoteFIleSystemProvider.ts` : handle the disconnected issue
=> Enable socketio reconnect

src/core/remoteFileSystemProvider.ts
Fix the reconnect problem as mentioned in #23
=> fix reconnect

src/api/base.ts, src/api/socketio.ts, src/api/socketioAlt.ts, src/collaboration/clientManager.ts, src/compile/compileManager.ts, src/core/remoteFileSystemProvider.ts
This PR adds a new feature which avoids the usage of `socketio` and makes you invisible from other's view.
=> New feature: Invisible Mode

docs/wiki.md, package.json, src/compile/compileManager.ts, src/extension.ts, src/scm/localReplicaSCM.ts
=> [Feature] allow to enable compile and preview in local folder

CHANGELOG.md, package-lock.json, package.json
=> build: bump v0.8.0

package.json
=> fix: typo in keybindings for mac

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.8.1

src/core/projectManagerProvider.ts, src/scm/scmCollectionProvider.ts
> resolves #80 
chore: only use warning message for input required.
=> chore: only use warning message for input required

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.9.0

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.9.1

src/scm/historyViewProvider.ts
=> [FIX] history diff compare in reversed order

src/api/base.ts, src/scm/historyViewProvider.ts
=> [Feat] support multi-file diff

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.10.0

package.json
=> [Feature] add Icon for compile and view pdf

l10n/bundle.l10n.json, src/api/socketioAlt.ts, src/intellisense/langMisspellingCheckProvider.ts
> resolves #109 
```
local version: 61 latest version: 62 pathname: main.tex
local version: 62 latest version: 69 pathname: main.tex
local version: 62 latest version: 73 pathname: main.tex   <-- race patch
local version: 69 latest version: 77 pathname: main.tex
local version: 73 latest version: 77 pathname: main.tex
local version: 73 latest version: 77 pathname: main.tex   <-- duplicate patch
```
=> [FIX] Invisible Mode Unexpected Behavior

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.11.0

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.12.0

l10n/bundle.l10n.json, src/core/projectManagerProvider.ts, src/utils/globalStateManager.ts
resolve #126  
+ Raise cookie expired error in `src\utils\globalStateManager.ts` 
+ Catch error and automatically logout in `src\core\projectManagerProvider.ts`
=> feat: automatically logout if cookie expired

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.12.1

src/core/remoteFileSystemProvider.ts, src/scm/localReplicaSCM.ts, src/scm/scmCollectionProvider.ts
> resolves #134 
> resolves #140
=> fix(scm): local replica sync cache using hash

src/compile/compileManager.ts, src/core/remoteFileSystemProvider.ts, src/intellisense/langCompletionProvider.ts
=> fix: save dirty files before compile

src/intellisense/texDocumentParseUtility.ts
> resolve #146 
Add missing `\addbibresource` in bib file searching
=> [FIX]: missing biblatex completion

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.12.3

README.md
update README.md with compatibility With Overleaf Community 5.0.4
=> [Docs]: update README.md with compatibility With Overleaf Community 5.0.4

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.13.0

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.13.1

src/core/pdfViewEditorProvider.ts, views/pdf-viewer/vendor/pdfjs-3.10.111-dist.patch
=> feat(pdfjs): remove pdfjs page border

src/scm/localReplicaSCM.ts
=> chore(scm): local replica update default ignore patterns

package-lock.json, package.json, src/intellisense/index.ts, src/intellisense/langCompletionProvider.ts
=> feat(intellisense): fuzzy filterText match

src/intellisense/texDocumentParseUtility.ts, src/intellisense/texDocumentSymbolProvider.ts
=> [Fix] missing chapter in outline

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.14.0

src/scm/index.ts, src/scm/localReplicaSCM.ts, src/scm/scmCollectionProvider.ts
=> feat(scm): allow to set local replia folder name

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.15.1

src/intellisense/langCompletionProvider.ts
=> fix: document link provider completed with common postfix

src/api/base.ts, src/core/remoteFileSystemProvider.ts
=> fix: syncpdf compatible with latest version

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.15.2

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.15.3

CHANGELOG.md, package-lock.json, package.json
=> ci(release): bump v0.15.4

package-lock.json, package.json
> resolve #233 
- Update `unified-latex` to latest version (>1.8.0) to resolve formatter issues
Reference: https://github.com/siefkenj/unified-latex/issues/107
- Fix Prettier version specification (previously accidentally set to @unified-latex/unified-latex-prettier@^2.4.2)
=> [Fix] Formatter for \author
