src/api/base.ts

It seems when acquire the compiled result, the url will have double "//" which somtime cause a 404.

fix: getFileFromClsi

---

src/api/base.ts
src/extension.ts
src/utils/compileManager.ts
views/vscode-pdf-viewer.js

This requests mainly contains the impementation of _translation_ from mouse click position to PDF point.
In `src/api/base.ts`, the additional tokern is added when call for update to Overleaf server.
In  `src/extension.ts`, introduce some data type translation.
In `views/vscode-pdf-viewer.js`, the main _translation_ function is implemented.
in `src/utils/compileManager.ts`, the reverse sync followed https://github.com/iamhyc/Overleaf-Workshop/pull/9#discussion_r1319470002 is added. However, simply selection seems to not able to jump to tex location, additional reveal Range is added. Besides, it seems selection api will select line number + 1 rather than line number, the input line number of api is minused 1 here.

update reverse sync

---

package-lock.json
package.json
src/provider/remoteFileSystemProvider.ts

Modify `remoteFileSystemProvider`  with out-of-sync handle.
When the updating version do not match the cache version, apply an immediate reload.
PS. When the overleaf website user modify the file content, the local cache update, which will not immedatelly apply to the vscode if there exist some modification of same position by vscode users (which is not compiled, that is the update is not sent to remote).  Thus when generating the following update, the remote update will be erased by comparing the local cache and current wriiten file.

handle out-of-sync

---

src/api/base.ts

Enable login with single session cookie in `src/api/base.ts`
Now agent will request the server to return GCLB cookie before actual login.

robust cookie login

---

src/api/socketio.ts
src/collaboration/clientManager.ts
src/provider/remoteFileSystemProvider.ts

**PR Content**:  Fix the client agent multiple register problem as #23 mentioned.
**File Modification**:
+ In `src/api/socketio.ts`, using an stored array to resume handlers in same case will not overwritten after resume.
+ In `src/collaboration/clientManager.ts`, add disconnecting indicator.
+ In `src/provider/remoteFileSystemProvider.ts`,   instead of re-applying the init function which register clientAgent once more, a partial init is applied.

fix: clientAgent multiple register

---

src/intellisense/langIntellisenseProvider.ts

As #32  mentioned, the problem comes from incorrect word deletion.
We only need to remove trigger character since in using custom Intelligence, the trigger character (non-word character) is not replaced automatrically.

fix: commond completion

---

src/api/socketio.ts

As #46 mentioned, the reconnection problem can be solved by adding a timeout promise to `jointProject`.

fix:reconnect issue

---

package-lock.json
package.json
src/extension.ts
src/intellisense/langIntellisenseProvider.ts
src/intellisense/texDocFormatter.ts
src/intellisense/texDocSymbolProvider.ts

ADD an outline symbol provider and a default code formatter.
After get a document:
`document` --> `genTexElements()` --> `TeXElement[]` --> `elementsToSymbols()` --> `vscode.DocumentSymbol[]`
The `document` will first be parsed by `parse` into `Ast.node`, after that, `parseNode()` iteratively parse the node into a vector `TeXElement[]`. The `TeXElement[]` will be further propossed by `hierarchyStructFormat()` to offer a structured symbol tree.
During `genTexElements()`, three helpers `macroToStr()`,  `envToStr()` and `argContentToStr()` convert arguments of node, which parsed by unified-latex from document, to string.
Use the prettier offered by `unified-latex`

Code format

---

.github/workflows/README.md
.github/workflows/vsce-publish.yml

This PR adds a github action `vsce-publish` to automatically publish then extension to Marketplace when version tag is pushed on the `master` branch.
This PR also updates the workflows documentation in `.github/workflows/READM.md` .

Auto vsce publish

---

src/core/projectManagerProvider.ts
src/scm/scmCollectionProvider.ts

> resolves #80 
This PR regulates the code convention: All message boxes which require user input should use `WarningMessage` or `ErrorMessage` considering the severity of aftereffect.

fix: use error/warning popup for user input

---

src/core/remoteFileSystemProvider.ts
src/scm/localReplicaSCM.ts

[Fix] Local Replica Unexpected Behavior

---

src/intellisense/langIntellisenseProvider.ts
src/intellisense/texDocSymbolCache.ts
src/intellisense/texDocSymbolProvider.ts

> resolve #61 
This PR is aim to support bib entry completition from bib file.
In this file, define type -- `FileCache`, Class -- `ProjectCache`
- `FileCache`, stores the parsed file content:
-  `filePath`, used to identify each file.
-  `fileContent`, a copy of `.tex` file content
-  `texElements`, symbols extracted from `parseNode` in `texDocSymbolProvider.ts`
-  `bibFilePaths`, the file name of bib file used in this `.tex` file
-  `childrenPaths`, the file name of inported file
- `ProjectCache`, the cache to store the data from project
- `fileNodeCache` which is a map `Map<string, FileNode>` used to reduced the time required to get each node.
- Func `updateCache`, update node into cache
- Func `getBibFilePaths`, get paths of bib file given the root path
In this file, the …

[Intellisense] Support citation intellisense from .bib file

---

package.json

> resolves #97 
Only use PDF viewer for URI with `overleaf-workshop` scheme.

[FIX] restrict pdf viewer actiation scope

---

src/intellisense/texDocumentParseUtility.ts
src/intellisense/texDocumentSymbolProvider.ts

> resolve #116 
The macro folding is read from texElements
Thanks to @iamhyc , this is done by following https://github.com/iamhyc/LaTeX-Workshop/commit/d1a078d9b63a34c9cda9ff5d1042c8999030e6e1

[Feature]: Enable Folding for Macro and Environment 

---

src/intellisense/langCompletionProvider.ts

> resolves #133 
This PR will filter the duplicate entries in references return from overleaf server.

fix(intellisense): filter duplicate reference entries

---

src/intellisense/langCompletionProvider.ts

> resolve #165 
Make cite completion triggered by command beginwith or endwith `cite`

[FIX]: autocompletion completion for command beginwith or endwith cite

---

src/compile/compileManager.ts
src/core/remoteFileSystemProvider.ts

[Feature]: enable compiling different root file when opened

---

src/compile/compileManager.ts
src/core/pdfViewEditorProvider.ts
src/intellisense/langMisspellingCheckProvider.ts

- Fix PDF not updated when drag PDF to new window
- When we drag a PDF tab to a new window by https://code.visualstudio.com/docs/getstarted/userinterface#_floating-windows , the webview will reload, and the content inside it is not retained. So although it is declared as `retainContextWhenHidden` https://github.com/iamhyc/Overleaf-Workshop/blob/master/src/core/pdfViewEditorProvider.ts#L97-L99 , it does not apply to the situation when we drag it to new window.
- So it is a full reload for webview, and we would better send the pdf content to it when it is ready (again). Because the doc has not changed (Same code, same pdf), it will not trigger event to update the pdf into webview. 
- At the first time of pdf is ready, the conent is empty, so …

[Fix] Fix PDF not updated when drag PDF to new window. Change strategy when sync code

---

src/intellisense/langIntellisenseProvider.ts

> resolve #262 
The Code Spell Checker is automatically enabled when the overleaf-workshop extension activates. 
Configuration modifications occur during the IntelliSense provider initialization globally (since the workspace setting would be automatically synced with remote server and currently no filter in online mode is available).
The performance is verified under:
+ [x] official overleaf server
+ [x] community overleaf server (the spell checker in overleaf-workshop would be first place)
+ [x] local replica
**Note:** If the Code Spell Checker extension is not installed, this approach gracefully skips configuration due to VS Code's built-in API logic.

[Feature]: Enable Code Spell Checker by Default

---

.github/workflows/vsce-package.yml

Potential fix for [https://github.com/iamhyc/Overleaf-Workshop/security/code-scanning/3](https://github.com/iamhyc/Overleaf-Workshop/security/code-scanning/3)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will define the least privileges required for the workflow to function correctly. Based on the tasks in the workflow, the following permissions are needed:
- `contents: read` for accessing the repository's contents.
- `packages: write` for uploading the artifact.
The `permissions` block will be added after the `name` field at the top of the file.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 3: Workflow does not contain permissions

---

src/core/projectManagerProvider.ts
src/core/remoteFileSystemProvider.ts

This PR improves the robustness of project name parsing in the Overleaf Workshop VS Code extension.  
**Main changes:**
- **Fixes an issue where project names containing special characters (such as `[]`) could not be parsed correctly.**
- In `parseUri` (remoteFileSystemProvider.ts), project name is now decoded from the path if present, or falls back to the `projectName` query parameter if missing.
- Ensures that project URIs are always generated with `encodeURIComponent` for the project name (projectManagerProvider.ts).
**This resolves the bug where projects with names like `[test]` could not be opened or used in the extension.**
---
#283

[Fix] project name parsing for special characters in Overleaf project URIs

---

src/core/remoteFileSystemProvider.ts

`removeEntity()` and `insertEntity()` both operate based on the `FileEntity._id`. If we rename a file, its `_id` stays the same. We must remove first and then insert. Otherwise the insert doesn't do anything and the file just gets removed.
This fixes #289

fix: file rename
